# Generated by Django 5.2.7 on 2025-10-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('idEleve', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('idTuteur', models.AutoField(primary_key=True, serialize=False)),
                ('tuteur', models.CharField(max_length=100)),
                ('professionTuteur', models.CharField(max_length=100)),
                ('contactTuteur', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('idInscription', models.AutoField(primary_key=True, serialize=False)),
                ('dateInscription', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('classeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.classe')),
                ('eleveRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='tuteurRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.tuteur'),
        ),
    ]
