# Generated by Django 5.2.7 on 2025-10-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('idDiscipline', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('idEnseignant', models.AutoField(primary_key=True, serialize=False)),
                ('nomEnseignant', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('idMatiere', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('disRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('idEnseignement', models.AutoField(primary_key=True, serialize=False)),
                ('EnsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.enseignant')),
                ('matRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='MatiereNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeurCoef', models.IntegerField()),
                ('matRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.matiere')),
                ('nivRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='EnseignementClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.enseignant')),
                ('classeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.classe')),
                ('matRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.matiere')),
            ],
            options={
                'unique_together': {('EnsRef', 'matRef', 'classeRef')},
            },
        ),
    ]
