# Generated by Django 5.2.7 on 2025-10-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('idAnnee', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('libelle', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('libelle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cycleRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('idClasse', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('anneeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.anneescolaire')),
                ('nivRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.niveau')),
            ],
        ),
    ]
