# Generated by Django 5.2.7 on 2025-10-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('structure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('numPaiement', models.AutoField(primary_key=True, serialize=False)),
                ('datePaiement', models.DateField()),
                ('modePaiement', models.CharField(max_length=50)),
                ('montantTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('idTarif', models.AutoField(primary_key=True, serialize=False)),
                ('typePaiement', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anneeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.anneescolaire')),
                ('nivRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementDetail',
            fields=[
                ('idDetail', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(blank=True, max_length=50, null=True)),
                ('estPaye', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3)),
                ('paiementRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.paiement')),
                ('tarifRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paiements.tarification')),
            ],
        ),
    ]
