# Generated by Django 5.2.7 on 2025-10-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('enseignement', '0001_initial'),
        ('structure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('idBulletin', models.AutoField(primary_key=True, serialize=False)),
                ('InsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('idExamen', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('anneeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('idNote', models.AutoField(primary_key=True, serialize=False)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appreciation', models.TextField()),
                ('InsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.inscription')),
                ('matRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.classe')),
                ('examRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen')),
            ],
            options={
                'unique_together': {('classeRef', 'examRef')},
            },
        ),
        migrations.CreateModel(
            name='MatiereExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen')),
                ('matRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.matiere')),
            ],
            options={
                'unique_together': {('matRef', 'examRef')},
            },
        ),
    ]
