# Generated by Django 5.2.7 on 2025-10-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avertissement',
            fields=[
                ('idAvertissement', models.AutoField(primary_key=True, serialize=False)),
                ('dateAvert', models.DateField()),
                ('description', models.TextField()),
                ('InsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('idSanction', models.AutoField(primary_key=True, serialize=False)),
                ('type_sanction', models.CharField(max_length=100)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('InsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.inscription')),
            ],
        ),
    ]
