# Generated by Django 5.2.7 on 2025-10-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignement', '__first__'),
        ('structure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('idCreneau', models.AutoField(primary_key=True, serialize=False)),
                ('heureDebut', models.TimeField()),
                ('heureFin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneauRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplois.creneau')),
                ('disRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='EmploisDuTemps',
            fields=[
                ('idEDT', models.AutoField(primary_key=True, serialize=False)),
                ('classeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('libelle', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('edtRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplois.emploisdutemps')),
            ],
        ),
        migrations.AddField(
            model_name='creneau',
            name='jourRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplois.jour'),
        ),
        migrations.CreateModel(
            name='Sceance',
            fields=[
                ('idSceance', models.AutoField(primary_key=True, serialize=False)),
                ('EnsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.enseignant')),
                ('creneauRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplois.creneau')),
            ],
        ),
    ]
